apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do date >> /srv/nfs/data.txt; sleep 5; done"]
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: nfs-storage
          mountPath: /srv/nfs
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs

          

